POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "name":"abdo",
    "email":"abdo@example.com",
    "password":"12345678",
    "age":33
}

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email":"abdo@example.com",
    "password":"12345678"
}

###
GET http://localhost:3000/api/users/posts
Authorization: Bearir eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia2hhbGVkIiwiZW1haWwiOiJraGFsZWRAZXhhbXBsZS5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCQzYVViai5DbVNONVFtTGpYV04yUktPTmI1N1A4a0V5emxIM2Y0aGFQTmF0VDhZYlFELmgzMiIsImlhdCI6MTU5ODk2NjUxNn0.9iu4lvijMUWLScl96UP9SHdLZtN7vOHqpFhF59o_kR4

####

GET http://localhost:3000/api/courses